import { IProduct } from '@/types/entries/product';

export default [
    {
        id: 0,
        teacher_id: 15,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 134,
            currency: 'RUB',
        },
    },
    {
        id: 1,
        teacher_id: 28,
        class_type_id: 3,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 130,
            currency: 'RUB',
        },
    },
    {
        id: 2,
        teacher_id: 22,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 140,
            currency: 'RUB',
        },
    },
    {
        id: 3,
        teacher_id: 18,
        class_type_id: 1,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 157,
            currency: 'RUB',
        },
    },
    {
        id: 4,
        teacher_id: 16,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 168,
            currency: 'RUB',
        },
    },
    {
        id: 5,
        teacher_id: 12,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 154,
            currency: 'RUB',
        },
    },
    {
        id: 6,
        teacher_id: 26,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 160,
            currency: 'RUB',
        },
    },
    {
        id: 7,
        teacher_id: 23,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 126,
            currency: 'RUB',
        },
    },
    {
        id: 8,
        teacher_id: 8,
        class_type_id: 3,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 188,
            currency: 'RUB',
        },
    },
    {
        id: 9,
        teacher_id: 13,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 168,
            currency: 'RUB',
        },
    },
    {
        id: 10,
        teacher_id: 0,
        class_type_id: 3,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 135,
            currency: 'RUB',
        },
    },
    {
        id: 11,
        teacher_id: 11,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 163,
            currency: 'RUB',
        },
    },
    {
        id: 12,
        teacher_id: 17,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 192,
            currency: 'RUB',
        },
    },
    {
        id: 13,
        teacher_id: 22,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 167,
            currency: 'RUB',
        },
    },
    {
        id: 14,
        teacher_id: 8,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 114,
            currency: 'RUB',
        },
    },
    {
        id: 15,
        teacher_id: 24,
        class_type_id: 3,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 160,
            currency: 'RUB',
        },
    },
    {
        id: 16,
        teacher_id: 25,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 164,
            currency: 'RUB',
        },
    },
    {
        id: 17,
        teacher_id: 25,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 180,
            currency: 'RUB',
        },
    },
    {
        id: 18,
        teacher_id: 3,
        class_type_id: 0,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 186,
            currency: 'RUB',
        },
    },
    {
        id: 19,
        teacher_id: 13,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 129,
            currency: 'RUB',
        },
    },
    {
        id: 20,
        teacher_id: 23,
        class_type_id: 2,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 153,
            currency: 'RUB',
        },
    },
    {
        id: 21,
        teacher_id: 24,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 178,
            currency: 'RUB',
        },
    },
    {
        id: 22,
        teacher_id: 11,
        class_type_id: 3,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 192,
            currency: 'RUB',
        },
    },
    {
        id: 23,
        teacher_id: 15,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 166,
            currency: 'RUB',
        },
    },
    {
        id: 24,
        teacher_id: 20,
        class_type_id: 0,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 192,
            currency: 'RUB',
        },
    },
    {
        id: 25,
        teacher_id: 7,
        class_type_id: 3,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 111,
            currency: 'RUB',
        },
    },
    {
        id: 26,
        teacher_id: 29,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 184,
            currency: 'RUB',
        },
    },
    {
        id: 27,
        teacher_id: 20,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 127,
            currency: 'RUB',
        },
    },
    {
        id: 28,
        teacher_id: 23,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 155,
            currency: 'RUB',
        },
    },
    {
        id: 29,
        teacher_id: 4,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 147,
            currency: 'RUB',
        },
    },
    {
        id: 30,
        teacher_id: 5,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 168,
            currency: 'RUB',
        },
    },
    {
        id: 31,
        teacher_id: 15,
        class_type_id: 2,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 154,
            currency: 'RUB',
        },
    },
    {
        id: 32,
        teacher_id: 18,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 191,
            currency: 'RUB',
        },
    },
    {
        id: 33,
        teacher_id: 11,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 135,
            currency: 'RUB',
        },
    },
    {
        id: 34,
        teacher_id: 9,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 113,
            currency: 'RUB',
        },
    },
    {
        id: 35,
        teacher_id: 28,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 199,
            currency: 'RUB',
        },
    },
    {
        id: 36,
        teacher_id: 12,
        class_type_id: 3,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 172,
            currency: 'RUB',
        },
    },
    {
        id: 37,
        teacher_id: 14,
        class_type_id: 3,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 161,
            currency: 'RUB',
        },
    },
    {
        id: 38,
        teacher_id: 25,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 178,
            currency: 'RUB',
        },
    },
    {
        id: 39,
        teacher_id: 23,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 163,
            currency: 'RUB',
        },
    },
    {
        id: 40,
        teacher_id: 7,
        class_type_id: 2,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 115,
            currency: 'RUB',
        },
    },
    {
        id: 41,
        teacher_id: 14,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 186,
            currency: 'RUB',
        },
    },
    {
        id: 42,
        teacher_id: 0,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 172,
            currency: 'RUB',
        },
    },
    {
        id: 43,
        teacher_id: 10,
        class_type_id: 3,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 180,
            currency: 'RUB',
        },
    },
    {
        id: 44,
        teacher_id: 13,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 156,
            currency: 'RUB',
        },
    },
    {
        id: 45,
        teacher_id: 15,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 101,
            currency: 'RUB',
        },
    },
    {
        id: 46,
        teacher_id: 7,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 177,
            currency: 'RUB',
        },
    },
    {
        id: 47,
        teacher_id: 26,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 166,
            currency: 'RUB',
        },
    },
    {
        id: 48,
        teacher_id: 5,
        class_type_id: 3,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 197,
            currency: 'RUB',
        },
    },
    {
        id: 49,
        teacher_id: 5,
        class_type_id: 2,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 146,
            currency: 'RUB',
        },
    },
    {
        id: 50,
        teacher_id: 18,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 169,
            currency: 'RUB',
        },
    },
    {
        id: 51,
        teacher_id: 2,
        class_type_id: 0,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 182,
            currency: 'RUB',
        },
    },
    {
        id: 52,
        teacher_id: 26,
        class_type_id: 3,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 110,
            currency: 'RUB',
        },
    },
    {
        id: 53,
        teacher_id: 15,
        class_type_id: 3,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 157,
            currency: 'RUB',
        },
    },
    {
        id: 54,
        teacher_id: 26,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 149,
            currency: 'RUB',
        },
    },
    {
        id: 55,
        teacher_id: 28,
        class_type_id: 2,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 103,
            currency: 'RUB',
        },
    },
    {
        id: 56,
        teacher_id: 18,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 138,
            currency: 'RUB',
        },
    },
    {
        id: 57,
        teacher_id: 1,
        class_type_id: 3,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 184,
            currency: 'RUB',
        },
    },
    {
        id: 58,
        teacher_id: 5,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 105,
            currency: 'RUB',
        },
    },
    {
        id: 59,
        teacher_id: 15,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 198,
            currency: 'RUB',
        },
    },
    {
        id: 60,
        teacher_id: 10,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 180,
            currency: 'RUB',
        },
    },
    {
        id: 61,
        teacher_id: 10,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 144,
            currency: 'RUB',
        },
    },
    {
        id: 62,
        teacher_id: 10,
        class_type_id: 2,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 188,
            currency: 'RUB',
        },
    },
    {
        id: 63,
        teacher_id: 18,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 149,
            currency: 'RUB',
        },
    },
    {
        id: 64,
        teacher_id: 7,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 124,
            currency: 'RUB',
        },
    },
    {
        id: 65,
        teacher_id: 25,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 200,
            currency: 'RUB',
        },
    },
    {
        id: 66,
        teacher_id: 26,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 108,
            currency: 'RUB',
        },
    },
    {
        id: 67,
        teacher_id: 6,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 157,
            currency: 'RUB',
        },
    },
    {
        id: 68,
        teacher_id: 27,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 164,
            currency: 'RUB',
        },
    },
    {
        id: 69,
        teacher_id: 4,
        class_type_id: 0,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 148,
            currency: 'RUB',
        },
    },
    {
        id: 70,
        teacher_id: 16,
        class_type_id: 1,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 199,
            currency: 'RUB',
        },
    },
    {
        id: 71,
        teacher_id: 18,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 123,
            currency: 'RUB',
        },
    },
    {
        id: 72,
        teacher_id: 6,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 115,
            currency: 'RUB',
        },
    },
    {
        id: 73,
        teacher_id: 13,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 125,
            currency: 'RUB',
        },
    },
    {
        id: 74,
        teacher_id: 28,
        class_type_id: 3,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 194,
            currency: 'RUB',
        },
    },
    {
        id: 75,
        teacher_id: 10,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 170,
            currency: 'RUB',
        },
    },
    {
        id: 76,
        teacher_id: 0,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 167,
            currency: 'RUB',
        },
    },
    {
        id: 77,
        teacher_id: 8,
        class_type_id: 2,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 110,
            currency: 'RUB',
        },
    },
    {
        id: 78,
        teacher_id: 3,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 169,
            currency: 'RUB',
        },
    },
    {
        id: 79,
        teacher_id: 10,
        class_type_id: 1,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 196,
            currency: 'RUB',
        },
    },
    {
        id: 80,
        teacher_id: 23,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 191,
            currency: 'RUB',
        },
    },
    {
        id: 81,
        teacher_id: 28,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 112,
            currency: 'RUB',
        },
    },
    {
        id: 82,
        teacher_id: 9,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 155,
            currency: 'RUB',
        },
    },
    {
        id: 83,
        teacher_id: 26,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 186,
            currency: 'RUB',
        },
    },
    {
        id: 84,
        teacher_id: 7,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 151,
            currency: 'RUB',
        },
    },
    {
        id: 85,
        teacher_id: 2,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 127,
            currency: 'RUB',
        },
    },
    {
        id: 86,
        teacher_id: 5,
        class_type_id: 0,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 106,
            currency: 'RUB',
        },
    },
    {
        id: 87,
        teacher_id: 17,
        class_type_id: 2,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 127,
            currency: 'RUB',
        },
    },
    {
        id: 88,
        teacher_id: 21,
        class_type_id: 0,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 136,
            currency: 'RUB',
        },
    },
    {
        id: 89,
        teacher_id: 19,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 104,
            currency: 'RUB',
        },
    },
    {
        id: 90,
        teacher_id: 9,
        class_type_id: 0,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 117,
            currency: 'RUB',
        },
    },
    {
        id: 91,
        teacher_id: 6,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 150,
            currency: 'RUB',
        },
    },
    {
        id: 92,
        teacher_id: 4,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 181,
            currency: 'RUB',
        },
    },
    {
        id: 93,
        teacher_id: 2,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 182,
            currency: 'RUB',
        },
    },
    {
        id: 94,
        teacher_id: 27,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 183,
            currency: 'RUB',
        },
    },
    {
        id: 95,
        teacher_id: 9,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 133,
            currency: 'RUB',
        },
    },
    {
        id: 96,
        teacher_id: 19,
        class_type_id: 1,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 114,
            currency: 'RUB',
        },
    },
    {
        id: 97,
        teacher_id: 18,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 120,
            currency: 'RUB',
        },
    },
    {
        id: 98,
        teacher_id: 27,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 138,
            currency: 'RUB',
        },
    },
    {
        id: 99,
        teacher_id: 21,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 178,
            currency: 'RUB',
        },
    },
    {
        id: 100,
        teacher_id: 3,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 189,
            currency: 'RUB',
        },
    },
    {
        id: 101,
        teacher_id: 3,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 150,
            currency: 'RUB',
        },
    },
    {
        id: 102,
        teacher_id: 13,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 143,
            currency: 'RUB',
        },
    },
    {
        id: 103,
        teacher_id: 22,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 192,
            currency: 'RUB',
        },
    },
    {
        id: 104,
        teacher_id: 13,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 133,
            currency: 'RUB',
        },
    },
    {
        id: 105,
        teacher_id: 29,
        class_type_id: 3,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 134,
            currency: 'RUB',
        },
    },
    {
        id: 106,
        teacher_id: 1,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 192,
            currency: 'RUB',
        },
    },
    {
        id: 107,
        teacher_id: 25,
        class_type_id: 2,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 189,
            currency: 'RUB',
        },
    },
    {
        id: 108,
        teacher_id: 7,
        class_type_id: 2,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 124,
            currency: 'RUB',
        },
    },
    {
        id: 109,
        teacher_id: 21,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 154,
            currency: 'RUB',
        },
    },
    {
        id: 110,
        teacher_id: 16,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 114,
            currency: 'RUB',
        },
    },
    {
        id: 111,
        teacher_id: 0,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 159,
            currency: 'RUB',
        },
    },
    {
        id: 112,
        teacher_id: 28,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 103,
            currency: 'RUB',
        },
    },
    {
        id: 113,
        teacher_id: 14,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 181,
            currency: 'RUB',
        },
    },
    {
        id: 114,
        teacher_id: 7,
        class_type_id: 3,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 152,
            currency: 'RUB',
        },
    },
    {
        id: 115,
        teacher_id: 1,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 146,
            currency: 'RUB',
        },
    },
    {
        id: 116,
        teacher_id: 22,
        class_type_id: 2,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 124,
            currency: 'RUB',
        },
    },
    {
        id: 117,
        teacher_id: 14,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 155,
            currency: 'RUB',
        },
    },
    {
        id: 118,
        teacher_id: 16,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 166,
            currency: 'RUB',
        },
    },
    {
        id: 119,
        teacher_id: 26,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 170,
            currency: 'RUB',
        },
    },
    {
        id: 120,
        teacher_id: 11,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 198,
            currency: 'RUB',
        },
    },
    {
        id: 121,
        teacher_id: 17,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 148,
            currency: 'RUB',
        },
    },
    {
        id: 122,
        teacher_id: 6,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 171,
            currency: 'RUB',
        },
    },
    {
        id: 123,
        teacher_id: 15,
        class_type_id: 1,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 190,
            currency: 'RUB',
        },
    },
    {
        id: 124,
        teacher_id: 20,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 149,
            currency: 'RUB',
        },
    },
    {
        id: 125,
        teacher_id: 27,
        class_type_id: 1,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 197,
            currency: 'RUB',
        },
    },
    {
        id: 126,
        teacher_id: 29,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 113,
            currency: 'RUB',
        },
    },
    {
        id: 127,
        teacher_id: 4,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 147,
            currency: 'RUB',
        },
    },
    {
        id: 128,
        teacher_id: 6,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 104,
            currency: 'RUB',
        },
    },
    {
        id: 129,
        teacher_id: 28,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 155,
            currency: 'RUB',
        },
    },
    {
        id: 130,
        teacher_id: 14,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 140,
            currency: 'RUB',
        },
    },
    {
        id: 131,
        teacher_id: 28,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 174,
            currency: 'RUB',
        },
    },
    {
        id: 132,
        teacher_id: 23,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 149,
            currency: 'RUB',
        },
    },
    {
        id: 133,
        teacher_id: 1,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 184,
            currency: 'RUB',
        },
    },
    {
        id: 134,
        teacher_id: 0,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 140,
            currency: 'RUB',
        },
    },
    {
        id: 135,
        teacher_id: 0,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 156,
            currency: 'RUB',
        },
    },
    {
        id: 136,
        teacher_id: 25,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 180,
            currency: 'RUB',
        },
    },
    {
        id: 137,
        teacher_id: 13,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 119,
            currency: 'RUB',
        },
    },
    {
        id: 138,
        teacher_id: 5,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 104,
            currency: 'RUB',
        },
    },
    {
        id: 139,
        teacher_id: 11,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 193,
            currency: 'RUB',
        },
    },
    {
        id: 140,
        teacher_id: 4,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 156,
            currency: 'RUB',
        },
    },
    {
        id: 141,
        teacher_id: 22,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 122,
            currency: 'RUB',
        },
    },
    {
        id: 142,
        teacher_id: 28,
        class_type_id: 3,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 125,
            currency: 'RUB',
        },
    },
    {
        id: 143,
        teacher_id: 27,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 170,
            currency: 'RUB',
        },
    },
    {
        id: 144,
        teacher_id: 7,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 130,
            currency: 'RUB',
        },
    },
    {
        id: 145,
        teacher_id: 10,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 199,
            currency: 'RUB',
        },
    },
    {
        id: 146,
        teacher_id: 13,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 144,
            currency: 'RUB',
        },
    },
    {
        id: 147,
        teacher_id: 14,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 139,
            currency: 'RUB',
        },
    },
    {
        id: 148,
        teacher_id: 16,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 132,
            currency: 'RUB',
        },
    },
    {
        id: 149,
        teacher_id: 23,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 168,
            currency: 'RUB',
        },
    },
    {
        id: 150,
        teacher_id: 4,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 131,
            currency: 'RUB',
        },
    },
    {
        id: 151,
        teacher_id: 29,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 140,
            currency: 'RUB',
        },
    },
    {
        id: 152,
        teacher_id: 13,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 157,
            currency: 'RUB',
        },
    },
    {
        id: 153,
        teacher_id: 19,
        class_type_id: 0,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 199,
            currency: 'RUB',
        },
    },
    {
        id: 154,
        teacher_id: 22,
        class_type_id: 1,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 161,
            currency: 'RUB',
        },
    },
    {
        id: 155,
        teacher_id: 24,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 131,
            currency: 'RUB',
        },
    },
    {
        id: 156,
        teacher_id: 1,
        class_type_id: 2,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 104,
            currency: 'RUB',
        },
    },
    {
        id: 157,
        teacher_id: 9,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 184,
            currency: 'RUB',
        },
    },
    {
        id: 158,
        teacher_id: 13,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 121,
            currency: 'RUB',
        },
    },
    {
        id: 159,
        teacher_id: 8,
        class_type_id: 1,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 185,
            currency: 'RUB',
        },
    },
    {
        id: 160,
        teacher_id: 3,
        class_type_id: 2,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 167,
            currency: 'RUB',
        },
    },
    {
        id: 161,
        teacher_id: 16,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 107,
            currency: 'RUB',
        },
    },
    {
        id: 162,
        teacher_id: 11,
        class_type_id: 3,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 177,
            currency: 'RUB',
        },
    },
    {
        id: 163,
        teacher_id: 19,
        class_type_id: 0,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 161,
            currency: 'RUB',
        },
    },
    {
        id: 164,
        teacher_id: 6,
        class_type_id: 2,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 122,
            currency: 'RUB',
        },
    },
    {
        id: 165,
        teacher_id: 18,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 185,
            currency: 'RUB',
        },
    },
    {
        id: 166,
        teacher_id: 20,
        class_type_id: 0,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 155,
            currency: 'RUB',
        },
    },
    {
        id: 167,
        teacher_id: 15,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 172,
            currency: 'RUB',
        },
    },
    {
        id: 168,
        teacher_id: 20,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 105,
            currency: 'RUB',
        },
    },
    {
        id: 169,
        teacher_id: 21,
        class_type_id: 2,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 158,
            currency: 'RUB',
        },
    },
    {
        id: 170,
        teacher_id: 4,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 186,
            currency: 'RUB',
        },
    },
    {
        id: 171,
        teacher_id: 3,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 124,
            currency: 'RUB',
        },
    },
    {
        id: 172,
        teacher_id: 16,
        class_type_id: 1,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 178,
            currency: 'RUB',
        },
    },
    {
        id: 173,
        teacher_id: 13,
        class_type_id: 0,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 112,
            currency: 'RUB',
        },
    },
    {
        id: 174,
        teacher_id: 19,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 121,
            currency: 'RUB',
        },
    },
    {
        id: 175,
        teacher_id: 10,
        class_type_id: 0,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 130,
            currency: 'RUB',
        },
    },
    {
        id: 176,
        teacher_id: 12,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 110,
            currency: 'RUB',
        },
    },
    {
        id: 177,
        teacher_id: 3,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 177,
            currency: 'RUB',
        },
    },
    {
        id: 178,
        teacher_id: 29,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 101,
            currency: 'RUB',
        },
    },
    {
        id: 179,
        teacher_id: 4,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 179,
            currency: 'RUB',
        },
    },
    {
        id: 180,
        teacher_id: 14,
        class_type_id: 0,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 173,
            currency: 'RUB',
        },
    },
    {
        id: 181,
        teacher_id: 24,
        class_type_id: 1,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 186,
            currency: 'RUB',
        },
    },
    {
        id: 182,
        teacher_id: 6,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 156,
            currency: 'RUB',
        },
    },
    {
        id: 183,
        teacher_id: 5,
        class_type_id: 2,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 102,
            currency: 'RUB',
        },
    },
    {
        id: 184,
        teacher_id: 17,
        class_type_id: 0,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 134,
            currency: 'RUB',
        },
    },
    {
        id: 185,
        teacher_id: 6,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 173,
            currency: 'RUB',
        },
    },
    {
        id: 186,
        teacher_id: 11,
        class_type_id: 1,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 198,
            currency: 'RUB',
        },
    },
    {
        id: 187,
        teacher_id: 7,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 125,
            currency: 'RUB',
        },
    },
    {
        id: 188,
        teacher_id: 16,
        class_type_id: 3,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 158,
            currency: 'RUB',
        },
    },
    {
        id: 189,
        teacher_id: 3,
        class_type_id: 1,
        subject_id: 1,
        description: 'Описание',
        price: {
            amount: 121,
            currency: 'RUB',
        },
    },
    {
        id: 190,
        teacher_id: 15,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 109,
            currency: 'RUB',
        },
    },
    {
        id: 191,
        teacher_id: 15,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 112,
            currency: 'RUB',
        },
    },
    {
        id: 192,
        teacher_id: 15,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 168,
            currency: 'RUB',
        },
    },
    {
        id: 193,
        teacher_id: 8,
        class_type_id: 1,
        subject_id: 2,
        description: 'Описание',
        price: {
            amount: 169,
            currency: 'RUB',
        },
    },
    {
        id: 194,
        teacher_id: 20,
        class_type_id: 0,
        subject_id: 0,
        description: 'Описание',
        price: {
            amount: 169,
            currency: 'RUB',
        },
    },
    {
        id: 195,
        teacher_id: 29,
        class_type_id: 1,
        subject_id: 5,
        description: 'Описание',
        price: {
            amount: 150,
            currency: 'RUB',
        },
    },
    {
        id: 196,
        teacher_id: 21,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 152,
            currency: 'RUB',
        },
    },
    {
        id: 197,
        teacher_id: 3,
        class_type_id: 2,
        subject_id: 4,
        description: 'Описание',
        price: {
            amount: 134,
            currency: 'RUB',
        },
    },
    {
        id: 198,
        teacher_id: 20,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 109,
            currency: 'RUB',
        },
    },
    {
        id: 199,
        teacher_id: 5,
        class_type_id: 0,
        subject_id: 3,
        description: 'Описание',
        price: {
            amount: 180,
            currency: 'RUB',
        },
    },
] as IProduct[];